//
// Created by huhua on 2022/2/13.
//

#ifndef MH_TOOL_EXTERNAL_EASYBOT_INCLUDE_EASYBOT_UTIL_UTIL_COMM_H_
#define MH_TOOL_EXTERNAL_EASYBOT_INCLUDE_EASYBOT_UTIL_UTIL_COMM_H_
namespace eb {
long currentTimeInMillisecond();
}
#endif //MH_TOOL_EXTERNAL_EASYBOT_INCLUDE_EASYBOT_UTIL_UTIL_COMM_H_
